# Generated by h2py from /usr/include/netinet/in.h

# Included from cygwin/in.h

# Included from sys/socket.h

# Included from features.h

# Included from sys/cdefs.h

# Included from machine/_default_types.h

# Included from sys/features.h

# Included from _newlib_version.h
_NEWLIB_VERSION_H__ = 1
_NEWLIB_VERSION = "3.0.0"
__NEWLIB__ = 3
__NEWLIB_MINOR__ = 0
__NEWLIB_PATCHLEVEL__ = 0
_ATFILE_SOURCE = 1
_DEFAULT_SOURCE = 1
_ISOC99_SOURCE = 1
_ISOC11_SOURCE = 1
_POSIX_SOURCE = 1
_POSIX_C_SOURCE = 200809L
_XOPEN_SOURCE = 700
_XOPEN_SOURCE_EXTENDED = 1
_DEFAULT_SOURCE = 1
_POSIX_SOURCE = 1
_POSIX_C_SOURCE = 200809L
_POSIX_SOURCE = 1
_POSIX_C_SOURCE = 200809L
_POSIX_C_SOURCE = 200112L
_POSIX_C_SOURCE = 199506L
_POSIX_C_SOURCE = 2
_ATFILE_SOURCE = 1
__ATFILE_VISIBLE = 1
__ATFILE_VISIBLE = 0
__BSD_VISIBLE = 1
__BSD_VISIBLE = 0
__GNU_VISIBLE = 1
__GNU_VISIBLE = 0
__ISO_C_VISIBLE = 2011
__ISO_C_VISIBLE = 1999
__ISO_C_VISIBLE = 1990
__LARGEFILE_VISIBLE = 1
__LARGEFILE_VISIBLE = 0
__MISC_VISIBLE = 1
__MISC_VISIBLE = 0
__POSIX_VISIBLE = 200809
__POSIX_VISIBLE = 200112
__POSIX_VISIBLE = 199506
__POSIX_VISIBLE = 199309
__POSIX_VISIBLE = 199209
__POSIX_VISIBLE = 199009
__POSIX_VISIBLE = 0
__SVID_VISIBLE = 1
__SVID_VISIBLE = 0
__XSI_VISIBLE = 700
__XSI_VISIBLE = 600
__XSI_VISIBLE = 500
__XSI_VISIBLE = 4
__XSI_VISIBLE = 1
__XSI_VISIBLE = 0
__SSP_FORTIFY_LEVEL = 2
__SSP_FORTIFY_LEVEL = 1
__SSP_FORTIFY_LEVEL = 0
_POSIX_JOB_CONTROL = 1
_POSIX_SAVED_IDS = 1
_POSIX_VERSION = 199309L
_POSIX_ASYNCHRONOUS_IO = 1
_POSIX_FSYNC = 1
_POSIX_MAPPED_FILES = 1
_POSIX_MEMLOCK = 1
_POSIX_MEMLOCK_RANGE = 1
_POSIX_MEMORY_PROTECTION = 1
_POSIX_MESSAGE_PASSING = 1
_POSIX_MONOTONIC_CLOCK = 200112L
_POSIX_CLOCK_SELECTION = 200112L
_POSIX_PRIORITIZED_IO = 1
_POSIX_PRIORITY_SCHEDULING = 1
_POSIX_REALTIME_SIGNALS = 1
_POSIX_SEMAPHORES = 1
_POSIX_SHARED_MEMORY_OBJECTS = 1
_POSIX_SYNCHRONIZED_IO = 1
_POSIX_TIMERS = 1
_POSIX_BARRIERS = 200112L
_POSIX_READER_WRITER_LOCKS = 200112L
_POSIX_SPIN_LOCKS = 200112L
_POSIX_THREADS = 1
_POSIX_THREAD_ATTR_STACKADDR = 1
_POSIX_THREAD_ATTR_STACKSIZE = 1
_POSIX_THREAD_PRIORITY_SCHEDULING = 1
_POSIX_THREAD_PRIO_INHERIT = 1
_POSIX_THREAD_PRIO_PROTECT = 1
_POSIX_THREAD_PROCESS_SHARED = 1
_POSIX_THREAD_SAFE_FUNCTIONS = 1
_POSIX_SPAWN = 1
_POSIX_TIMEOUTS = 1
_POSIX_CPUTIME = 1
_POSIX_THREAD_CPUTIME = 1
_POSIX_SPORADIC_SERVER = 1
_POSIX_THREAD_SPORADIC_SERVER = 1
_POSIX_DEVICE_CONTROL = 1
_POSIX_DEVCTL_DIRECTION = 1
_POSIX_INTERRUPT_CONTROL = 1
_POSIX_ADVISORY_INFO = 1
_UNIX98_THREAD_MUTEX_ATTRIBUTES = 1
_POSIX_26_VERSION = 200312L
_POSIX_THREADS = 1
_POSIX_THREAD_PRIORITY_SCHEDULING = 1
_POSIX_JOB_CONTROL = 1
_POSIX_SAVED_IDS = 1
_POSIX_VERSION = 199009L
_POSIX_VERSION = 200809L
_POSIX2_VERSION = 200809L
_POSIX_VERSION = 200112L
_POSIX2_VERSION = 200112L
_POSIX_VERSION = 199506L
_POSIX2_VERSION = 199506L
_POSIX_VERSION = 199309L
_POSIX2_VERSION = 199209L
_POSIX_VERSION = 199009L
_POSIX2_VERSION = 199209L
_POSIX_VERSION = 199009L
_XOPEN_VERSION = __XSI_VISIBLE
_POSIX_ADVISORY_INFO = 200809L
_POSIX_ASYNCHRONOUS_IO = 200809L
_POSIX_BARRIERS = 200809L
_POSIX_CHOWN_RESTRICTED = 1
_POSIX_CLOCK_SELECTION = 200809L
_POSIX_CPUTIME = 200809L
_POSIX_FSYNC = 200809L
_POSIX_IPV6 = 200809L
_POSIX_JOB_CONTROL = 1
_POSIX_MAPPED_FILES = 200809L
_POSIX_MEMLOCK_RANGE = 200809L
_POSIX_MEMORY_PROTECTION = 200809L
_POSIX_MESSAGE_PASSING = 200809L
_POSIX_MONOTONIC_CLOCK = 200809L
_POSIX_NO_TRUNC = 1
_POSIX_PRIORITY_SCHEDULING = 200809L
_POSIX_RAW_SOCKETS = 200809L
_POSIX_READER_WRITER_LOCKS = 200809L
_POSIX_REALTIME_SIGNALS = 200809L
_POSIX_REGEXP = 1
_POSIX_SAVED_IDS = 1
_POSIX_SEMAPHORES = 200809L
_POSIX_SHARED_MEMORY_OBJECTS = 200809L
_POSIX_SHELL = 1
_POSIX_SPAWN = 200809L
_POSIX_SPIN_LOCKS = 200809L
_POSIX_SYNCHRONIZED_IO = 200809L
_POSIX_THREAD_ATTR_STACKADDR = 200809L
_POSIX_THREAD_ATTR_STACKSIZE = 200809L
_POSIX_THREAD_CPUTIME = 200809L
_POSIX_THREAD_PRIORITY_SCHEDULING = 200809L
_POSIX_THREAD_PROCESS_SHARED = 200809L
_POSIX_THREAD_SAFE_FUNCTIONS = 200809L
_POSIX_THREADS = 200809L
_POSIX_TIMEOUTS = 200809L
_POSIX_TIMERS = 200809L
_POSIX_VDISABLE = ord('\0')
_POSIX2_C_VERSION = _POSIX2_VERSION
_POSIX2_C_BIND = _POSIX2_VERSION
_POSIX2_C_DEV = _POSIX2_VERSION
_POSIX2_CHAR_TERM = _POSIX2_VERSION
_POSIX2_SW_DEV = _POSIX2_VERSION
_POSIX2_UPE = _POSIX2_VERSION
_POSIX_V6_ILP32_OFF32 = -1
_POSIX_V6_ILP32_OFFBIG = -1
_POSIX_V6_LP64_OFF64 = 1
_POSIX_V6_LPBIG_OFFBIG = 1
_POSIX_V6_ILP32_OFFBIG = 1
_POSIX_V6_LP64_OFF64 = -1
_POSIX_V6_LPBIG_OFFBIG = -1
_POSIX_V7_ILP32_OFF32 = _POSIX_V6_ILP32_OFF32
_POSIX_V7_ILP32_OFFBIG = _POSIX_V6_ILP32_OFFBIG
_POSIX_V7_LP64_OFF64 = _POSIX_V6_LP64_OFF64
_POSIX_V7_LPBIG_OFFBIG = _POSIX_V6_LPBIG_OFFBIG
_XBS5_ILP32_OFF32 = _POSIX_V6_ILP32_OFF32
_XBS5_ILP32_OFFBIG = _POSIX_V6_ILP32_OFFBIG
_XBS5_LP64_OFF64 = _POSIX_V6_LP64_OFF64
_XBS5_LPBIG_OFFBIG = _POSIX_V6_LPBIG_OFFBIG
_XOPEN_CRYPT = 1
_XOPEN_ENH_I18N = 1
_XOPEN_SHM = 1
__STDC_ISO_10646__ = 200910L
def __EXP(x): return __##x##__

def __EXP(x): return x


# Included from limits.h

# Included from bits/wordsize.h
_WORDSIZE_H = 1
__WORDSIZE = 64
__WORDSIZE_COMPAT32 = 1
__WORDSIZE = 32
MB_LEN_MAX = 8
SCHAR_MIN = (-128)
SCHAR_MAX = 127
UCHAR_MAX = 255
CHAR_MIN = 0
CHAR_MAX = 255
CHAR_MIN = (-128)
CHAR_MAX = 127
SHRT_MIN = (-32768)
SHRT_MAX = 32767
USHRT_MAX = 65535
__INT_MAX__ = 2147483647
INT_MAX = __INT_MAX__
__LONG_MAX__ = 9223372036854775807L
__LONG_MAX__ = 2147483647L
LONG_MAX = __LONG_MAX__
SSIZE_MAX = (__LONG_MAX__)
SSIZE_MAX = (__INT_MAX__)
AIO_LISTIO_MAX = 32
AIO_MAX = 8
AIO_PRIO_DELTA_MAX = 0
ARG_MAX = 32000
ATEXIT_MAX = 32
CHILD_MAX = 256
HOST_NAME_MAX = 255
IOV_MAX = 1024
LOGIN_NAME_MAX = 256
MQ_PRIO_MAX = INT_MAX
OPEN_MAX = 256
PAGESIZE = 65536
PAGE_SIZE = PAGESIZE
PTHREAD_DESTRUCTOR_ITERATIONS = 1
PTHREAD_KEYS_MAX = 1024
PTHREAD_STACK_MIN = 65536
RTSIG_MAX = 33
RTSIG_MAX = 1
SEM_VALUE_MAX = 1147483648
SIGQUEUE_MAX = 32
STREAM_MAX = 20
SYMLOOP_MAX = 10
TIMER_MAX = 32
TTY_NAME_MAX = 32
FILESIZEBITS = 64
LINK_MAX = 1024
MAX_CANON = 255
MAX_INPUT = 255
NAME_MAX = 255
PATH_MAX = 4096
PIPE_BUF = 4096
SYMLINK_MAX = (PATH_MAX - 1)
BC_BASE_MAX = 99
BC_DIM_MAX = 2048
BC_SCALE_MAX = 99
BC_STRING_MAX = 1000
EXPR_NEST_MAX = 32
LINE_MAX = 2048
NGROUPS_MAX = 1024
RE_DUP_MAX = 255
_POSIX_CLOCKRES_MIN = 20000000
_POSIX_AIO_LISTIO_MAX = 2
_POSIX_AIO_MAX = 1
_POSIX_ARG_MAX = 4096
_POSIX_CHILD_MAX = 25
_POSIX_DELAYTIMER_MAX = 32
_POSIX_HOST_NAME_MAX = 255
_POSIX_LINK_MAX = 8
_POSIX_LOGIN_NAME_MAX = 9
_POSIX_MAX_CANON = 255
_POSIX_MAX_INPUT = 255
_POSIX_MQ_OPEN_MAX = 8
_POSIX_MQ_PRIO_MAX = 32
_POSIX_NAME_MAX = 14
_POSIX_NGROUPS_MAX = 8
_POSIX_OPEN_MAX = 20
_POSIX_PATH_MAX = 256
_POSIX_PIPE_BUF = 512
_POSIX_RE_DUP_MAX = 255
_POSIX_RTSIG_MAX = 8
_POSIX_SEM_NSEMS_MAX = 256
_POSIX_SEM_VALUE_MAX = 32767
_POSIX_SIGQUEUE_MAX = 32
_POSIX_SSIZE_MAX = 32767
_POSIX_STREAM_MAX = 8
_POSIX_SS_REPL_MAX = 4
_POSIX_SYMLINK_MAX = 255
_POSIX_SYMLOOP_MAX = 8
_POSIX_THREAD_DESTRUCTOR_ITERATIONS = 4
_POSIX_THREAD_KEYS_MAX = 128
_POSIX_THREAD_THREADS_MAX = 64
_POSIX_TIMER_MAX = 32
_POSIX_TRACE_EVENT_NAME_MAX = 30
_POSIX_TRACE_NAME_MAX = 8
_POSIX_TRACE_SYS_MAX = 8
_POSIX_TRACE_USER_EVENT_MAX = 32
_POSIX_TTY_NAME_MAX = 9
_POSIX_TZNAME_MAX = 6
_POSIX2_BC_BASE_MAX = 99
_POSIX2_BC_DIM_MAX = 2048
_POSIX2_BC_SCALE_MAX = 99
_POSIX2_BC_STRING_MAX = 1000
_POSIX2_COLL_WEIGHTS_MAX = 2
_POSIX2_EXPR_NEST_MAX = 32
_POSIX2_LINE_MAX = 2048
_POSIX2_RE_DUP_MAX = 255
_XOPEN_IOV_MAX = 16
_XOPEN_NAME_MAX = 255
_XOPEN_PATH_MAX = 1024
NL_ARGMAX = 9
NL_LANGMAX = 14
NL_MSGMAX = 32767
NL_SETMAX = 255
NL_TEXTMAX = _POSIX2_LINE_MAX
NL_NMAX = INT_MAX
NZERO = 20
__have_longlong64 = 1
__have_long64 = 1
__have_long32 = 1
___int8_t_defined = 1
___int8_t_defined = 1
___int16_t_defined = 1
___int16_t_defined = 1
___int16_t_defined = 1
___int16_t_defined = 1
___int32_t_defined = 1
___int32_t_defined = 1
___int32_t_defined = 1
___int32_t_defined = 1
___int32_t_defined = 1
___int64_t_defined = 1
___int64_t_defined = 1
___int64_t_defined = 1
___int64_t_defined = 1
___int64_t_defined = 1
___int_least8_t_defined = 1
___int_least8_t_defined = 1
___int_least8_t_defined = 1
___int_least8_t_defined = 1
___int_least8_t_defined = 1
___int_least16_t_defined = 1
___int_least16_t_defined = 1
___int_least16_t_defined = 1
___int_least16_t_defined = 1
___int_least32_t_defined = 1
___int_least32_t_defined = 1
___int_least32_t_defined = 1
___int_least64_t_defined = 1
___int_least64_t_defined = 1
def __PMT(args): return args

__flexarr = [0]
def __has_attribute(x): return 0

def __has_feature(x): return 0

def __has_include(x): return 0

def __has_builtin(x): return 0

__GNUCLIKE_ASM = 3
__GNUCLIKE_ASM = 2
__GNUCLIKE___TYPEOF = 1
__GNUCLIKE___OFFSETOF = 1
__GNUCLIKE___SECTION = 1
__GNUCLIKE_CTOR_SECTION_HANDLING = 1
__GNUCLIKE_BUILTIN_CONSTANT_P = 1
__GNUCLIKE_BUILTIN_VARARGS = 1
__GNUCLIKE_BUILTIN_STDARG = 1
__GNUCLIKE_BUILTIN_VAALIST = 1
__GNUC_VA_LIST_COMPATIBILITY = 1
__GNUCLIKE_BUILTIN_NEXT_ARG = 1
__GNUCLIKE_BUILTIN_MEMCPY = 1
__CC_SUPPORTS_INLINE = 1
__CC_SUPPORTS___INLINE = 1
__CC_SUPPORTS___INLINE__ = 1
__CC_SUPPORTS___FUNC__ = 1
__CC_SUPPORTS_WARNING = 1
__CC_SUPPORTS_VARADIC_XXX = 1
__CC_SUPPORTS_DYNAMIC_ARRAY_INIT = 1
def __P(protos): return protos		 

def __STRING(x): return #x		 

def __XSTRING(x): return __STRING(x)	 

def __P(protos): return ()		 

def __STRING(x): return "x"

def __aligned(x): return __attribute__((__aligned__(x)))

def __section(x): return __attribute__((__section__(x)))

def __alloc_size(x): return __attribute__((__alloc_size__(x)))

def __alloc_align(x): return __attribute__((__alloc_align__(x)))

def _Alignas(x): return alignas(x)

def _Alignas(x): return __aligned(x)

def _Alignof(x): return alignof(x)

def _Alignof(x): return __alignof(x)

def __min_size(x): return static (x)

def __min_size(x): return (x)

def __predict_true(exp): return __builtin_expect((exp), 1)

def __predict_false(exp): return __builtin_expect((exp), 0)

def __predict_true(exp): return (exp)

def __predict_false(exp): return (exp)

def __format_arg(fmtarg): return __attribute__((__format_arg__ (fmtarg)))

def __lock_annotate(x): return __attribute__((x))

def __guarded_by(x): return __lock_annotate(guarded_by(x))

def __pt_guarded_by(x): return __lock_annotate(pt_guarded_by(x))


# Included from cygwin/socket.h

# Included from sys/types.h

# Included from _ansi.h

# Included from newlib.h
__NEWLIB_H__ = 1
_WANT_IO_C99_FORMATS = 1
_WANT_IO_LONG_LONG = 1
_WANT_IO_LONG_DOUBLE = 1
_WANT_IO_POS_ARGS = 1
_MB_CAPABLE = 1
_MB_LEN_MAX = 8
_ATEXIT_DYNAMIC_ALLOC = 1
_HAVE_LONG_DOUBLE = 1
_HAVE_CC_INHIBIT_LOOP_TO_LIBCALL = 1
_FVWRITE_IN_STREAMIO = 1
_FSEEK_OPTIMIZATION = 1
_WIDE_ORIENT = 1
_UNBUF_STREAM_OPT = 1

# Included from sys/config.h

# Included from machine/ieeefp.h
__OBSOLETE_MATH_DEFAULT = 0
__OBSOLETE_MATH_DEFAULT = 0
Sudden_Underflow = 1
def isfinite(__y): return \

def __ieeefp_isnanf(x): return 0

def __ieeefp_isinff(x): return 0

def __ieeefp_finitef(x): return 1

_FLOAT_ARG = float
_FLOAT_ARG = float
__OBSOLETE_MATH_DEFAULT = 0
__OBSOLETE_MATH_DEFAULT = 1
__OBSOLETE_MATH = __OBSOLETE_MATH_DEFAULT
MALLOC_ALIGNMENT = 16
H8300 = 1
INT_MAX = 32767
UINT_MAX = 65535
H8300 = 1
INT_MAX = __INT_MAX__
INT_MAX = 32767
INT_MAX = 2147483647
INT_MAX = __INT_MAX__
INT_MAX = __INT_MAX__
__LARGE64_FILES = 1
_LARGEFILE64_SOURCE = 1
INT_MAX = __INT_MAX__
MALLOC_ALIGNMENT = 8
__BUFSIZ__ = 16
__BUFSIZ__ = 256
_POINTER_INT = long
_POINTER_INT = int
INT_MAX = __INT_MAX__
MALLOC_ALIGNMENT = 8
_POINTER_INT = long
__BUFSIZ__ = 16
MALLOC_ALIGNMENT = 16
__INT_MAX__ = INT_MAX
__INT_MAX__ = 2147483647
__LONG_MAX__ = LONG_MAX
__LONG_MAX__ = 9223372036854775807L
__LONG_MAX__ = 2147483647L
_POINTER_INT = long
__RAND_MAX = 32767
__RAND_MAX = 0x7fffffff

# Included from cygwin/config.h
__SYMBOL_PREFIX = "_"
def _SYMSTR(x): return __SYMBOL_PREFIX #x

__FILENAME_MAX__ = 4096
__LARGE64_FILES = 1
__USE_INTERNAL_STAT64 = 1
__LINUX_ERRNO_EXTENSIONS__ = 1
_MB_EXTENDED_CHARSETS_ALL = 1
__HAVE_LOCALE_INFO__ = 1
__HAVE_LOCALE_INFO_EXTENDED__ = 1
_WANT_C99_TIME_FORMATS = 1
_GLIBC_EXTENSION = 1
_STDIO_BSD_SEMANTICS = 1
_USE_LONG_TIME_T = 1
DEFAULT_LOCALE = "C.UTF-8"
__FILENAME_MAX__ = 255
_READ_WRITE_RETURN_TYPE = int
_READ_WRITE_BUFSIZE_TYPE = int
_MB_EXTENDED_CHARSETS_ISO = 1
_MB_EXTENDED_CHARSETS_WINDOWS = 1
def _ATTRIBUTE(attrs): return __attribute__ (attrs)


# Included from machine/_types.h
__BIT_TYPES_DEFINED__ = 1

# Included from sys/_types.h

# Included from sys/lock.h
_TIME_T_ = long

# Included from sys/_stdint.h
__int8_t_defined = 1
__int16_t_defined = 1
__int32_t_defined = 1
__int64_t_defined = 1

# Included from machine/endian.h

# Included from machine/_endian.h

# Included from bits/endian.h
__BIG_ENDIAN = 4321
__LITTLE_ENDIAN = 1234
__BYTE_ORDER = __LITTLE_ENDIAN
_LITTLE_ENDIAN = __LITTLE_ENDIAN
_BIG_ENDIAN = __BIG_ENDIAN
_BYTE_ORDER = __BYTE_ORDER
def __htonl(_x): return __ntohl(_x)

def __htons(_x): return __ntohs(_x)

_QUAD_HIGHWORD = 1
_QUAD_LOWWORD = 0
_QUAD_HIGHWORD = 0
_QUAD_LOWWORD = 1
LITTLE_ENDIAN = _LITTLE_ENDIAN
BIG_ENDIAN = _BIG_ENDIAN
BYTE_ORDER = _BYTE_ORDER
def __bswap16(_x): return __builtin_bswap16(_x)

def __bswap32(_x): return __builtin_bswap32(_x)

def __bswap64(_x): return __builtin_bswap64(_x)

def __htonl(_x): return __bswap32(_x)

def __htons(_x): return __bswap16(_x)

def __ntohl(_x): return __bswap32(_x)

def __ntohs(_x): return __bswap16(_x)

def __htonl(_x): return ((__uint32_t)(_x))

def __htons(_x): return ((__uint16_t)(_x))

def __ntohl(_x): return ((__uint32_t)(_x))

def __ntohs(_x): return ((__uint16_t)(_x))


# Included from sys/select.h

# Included from sys/_sigset.h

# Included from sys/_timeval.h

# Included from sys/timespec.h

# Included from sys/_timespec.h
FD_SETSIZE = 64

# Included from sys/_pthreadtypes.h

# Included from machine/types.h

# Included from endian.h
LITTLE_ENDIAN = __LITTLE_ENDIAN
BIG_ENDIAN = __BIG_ENDIAN
BYTE_ORDER = __BYTE_ORDER

# Included from bits/byteswap.h
def htobe16(x): return __bswap_16(x)

def htobe32(x): return __bswap_32(x)

def htobe64(x): return __bswap_64(x)

def be16toh(x): return __bswap_16(x)

def be32toh(x): return __bswap_32(x)

def be64toh(x): return __bswap_64(x)

def htole16(x): return (x)

def htole32(x): return (x)

def htole64(x): return (x)

def le16toh(x): return (x)

def le32toh(x): return (x)

def le64toh(x): return (x)

def htobe16(x): return (x)

def htobe32(x): return (x)

def htobe64(x): return (x)

def be16toh(x): return (x)

def be32toh(x): return (x)

def be64toh(x): return (x)

def htole16(x): return __bswap_16(x)

def htole32(x): return __bswap_32(x)

def htole64(x): return __bswap_64(x)

def le16toh(x): return __bswap_16(x)

def le32toh(x): return __bswap_32(x)

def le64toh(x): return __bswap_64(x)

__BIT_TYPES_DEFINED__ = 1

# Included from sys/sysmacros.h
def major(dev): return gnu_dev_major(dev)

def minor(dev): return gnu_dev_minor(dev)

_SS_MAXSIZE = 128

# Included from asm/socket.h

# Included from cygwin/if.h
IFF_UP = 0x1
IFF_BROADCAST = 0x2
IFF_LOOPBACK = 0x8
IFF_POINTOPOINT = 0x10
IFF_NOTRAILERS = 0x20
IFF_RUNNING = 0x40
IFF_NOARP = 0x80
IFF_PROMISC = 0x100
IFF_MULTICAST = 0x1000
IFF_LOWER_UP = 0x10000
IFF_DORMANT = 0x20000
IFRF_FRIENDLYNAMESIZ = 260
IFNAMSIZ = 44
IF_NAMESIZE = IFNAMSIZ
IFHWADDRLEN = 6
IOCPARM_MASK = 0x7f
IOC_VOID = 0x20000000
IOC_OUT = 0x40000000
IOC_IN = 0x80000000
FIONBIO = 0x8004667e
SOL_SOCKET = 0xffff
SO_DEBUG = 0x0001
SO_ACCEPTCONN = 0x0002
SO_REUSEADDR = 0x0004
SO_KEEPALIVE = 0x0008
SO_DONTROUTE = 0x0010
SO_BROADCAST = 0x0020
SO_USELOOPBACK = 0x0040
SO_LINGER = 0x0080
SO_OOBINLINE = 0x0100
SO_PEERCRED = 0x0200
SO_PASSCRED = 0x0400
SO_SNDBUF = 0x1001
SO_RCVBUF = 0x1002
SO_SNDLOWAT = 0x1003
SO_RCVLOWAT = 0x1004
SO_SNDTIMEO = 0x1005
SO_RCVTIMEO = 0x1006
SO_ERROR = 0x1007
SO_TYPE = 0x1008

# Included from cygwin/sockios.h

# Included from sys/uio.h

# Included from cygwin/_ucred.h
def CMSG_ALIGN(len): return \

def CMSG_LEN(len): return \

def CMSG_SPACE(len): return \

def CMSG_FIRSTHDR(mhdr): return \

def CMSG_DATA(cmsg): return \

SCM_RIGHTS = 0x01
SCM_CREDENTIALS = 0x02
SOCK_STREAM = 1
SOCK_DGRAM = 2
SOCK_RAW = 3
SOCK_RDM = 4
SOCK_SEQPACKET = 5

# Included from cygwin/_socketflags.h
SOCK_NONBLOCK = 0x01000000
SOCK_CLOEXEC = 0x02000000
_SOCK_FLAG_MASK = 0xff000000
AF_UNSPEC = 0
AF_UNIX = 31
AF_UNIX = 1
AF_LOCAL = 1
AF_INET = 2
AF_IMPLINK = 3
AF_PUP = 4
AF_CHAOS = 5
AF_NS = 6
AF_ISO = 7
AF_OSI = AF_ISO
AF_ECMA = 8
AF_DATAKIT = 9
AF_CCITT = 10
AF_SNA = 11
AF_DECnet = 12
AF_DLI = 13
AF_LAT = 14
AF_HYLINK = 15
AF_APPLETALK = 16
AF_NETBIOS = 17
AF_INET6 = 23
AF_MAX = 32
PF_UNSPEC = AF_UNSPEC
PF_UNIX = AF_UNIX
PF_LOCAL = AF_LOCAL
PF_INET = AF_INET
PF_IMPLINK = AF_IMPLINK
PF_PUP = AF_PUP
PF_CHAOS = AF_CHAOS
PF_NS = AF_NS
PF_ISO = AF_ISO
PF_OSI = AF_OSI
PF_ECMA = AF_ECMA
PF_DATAKIT = AF_DATAKIT
PF_CCITT = AF_CCITT
PF_SNA = AF_SNA
PF_DECnet = AF_DECnet
PF_DLI = AF_DLI
PF_LAT = AF_LAT
PF_HYLINK = AF_HYLINK
PF_APPLETALK = AF_APPLETALK
PF_NETBIOS = AF_NETBIOS
PF_INET6 = AF_INET6
PF_MAX = AF_MAX
SOMAXCONN = 0x7fffffff
MSG_OOB = 0x1
MSG_PEEK = 0x2
MSG_DONTROUTE = 0x4
MSG_WAITALL = 0x8
MSG_DONTWAIT = 0x10
MSG_NOSIGNAL = 0x20
MSG_TRUNC = 0x0100
MSG_CTRUNC = 0x0200
MSG_BCAST = 0x0400
MSG_MCAST = 0x0800
MSG_CMSG_CLOEXEC = 0x1000
SOL_IP = 0
SOL_IPV6 = 41
SOL_IPX = 256
SOL_AX25 = 257
SOL_ATALK = 258
SOL_NETROM = 259
SOL_TCP = 6
SOL_UDP = 17
IPTOS_LOWDELAY = 0x10
IPTOS_THROUGHPUT = 0x08
IPTOS_RELIABILITY = 0x04
IP_DEFAULT_MULTICAST_TTL = 1
IP_DEFAULT_MULTICAST_LOOP = 1
IP_MAX_MEMBERSHIPS = 20
IP_OPTIONS = 1
IP_HDRINCL = 2
IP_TOS = 3
IP_TTL = 4
IP_MULTICAST_IF = 9
IP_MULTICAST_TTL = 10
IP_MULTICAST_LOOP = 11
IP_ADD_MEMBERSHIP = 12
IP_DROP_MEMBERSHIP = 13
IP_DONTFRAGMENT = 14
IP_ADD_SOURCE_MEMBERSHIP = 15
IP_DROP_SOURCE_MEMBERSHIP = 16
IP_BLOCK_SOURCE = 17
IP_UNBLOCK_SOURCE = 18
IP_PKTINFO = 19
IP_UNICAST_IF = 31
IPV6_HOPOPTS = 1
IPV6_UNICAST_HOPS = 4
IPV6_MULTICAST_IF = 9
IPV6_MULTICAST_HOPS = 10
IPV6_MULTICAST_LOOP = 11
IPV6_ADD_MEMBERSHIP = 12
IPV6_DROP_MEMBERSHIP = 13
IPV6_JOIN_GROUP = IPV6_ADD_MEMBERSHIP
IPV6_LEAVE_GROUP = IPV6_DROP_MEMBERSHIP
IPV6_DONTFRAG = 14
IPV6_PKTINFO = 19
IPV6_HOPLIMIT = 21
IPV6_CHECKSUM = 26
IPV6_V6ONLY = 27
IPV6_UNICAST_IF = 31
IPV6_RTHDR = 32
IPV6_RECVRTHDR = 38
IPV6_TCLASS = 39
IPV6_RECVTCLASS = 40
MCAST_JOIN_GROUP = 41
MCAST_LEAVE_GROUP = 42
MCAST_BLOCK_SOURCE = 43
MCAST_UNBLOCK_SOURCE = 44
MCAST_JOIN_SOURCE_GROUP = 45
MCAST_LEAVE_SOURCE_GROUP = 46
MCAST_INCLUDE = 0
MCAST_EXCLUDE = 1
_WS1_IP_OPTIONS = 1
_WS1_IP_MULTICAST_IF = 2
_WS1_IP_MULTICAST_TTL = 3
_WS1_IP_MULTICAST_LOOP = 4
_WS1_IP_ADD_MEMBERSHIP = 5
_WS1_IP_DROP_MEMBERSHIP = 6
_WS1_IP_TTL = 7
_WS1_IP_TOS = 8
_WS1_IP_DONTFRAGMENT = 9
IPX_TYPE = 1
TCP_NODELAY = 0x0001
TCP_MAXSEG = 2
SHUT_RD = 0
SHUT_WR = 1
SHUT_RDWR = 2
SOPRI_INTERACTIVE = 0
SOPRI_NORMAL = 1
SOPRI_BACKGROUND = 2

# Included from ssp/socket.h

# Included from ssp/ssp.h
def __ssp_real_(fun): return fun

def __ssp_real_(fun): return __ssp_real_ ## fun

def __ssp_real(fun): return __ssp_real_(fun)

def __ssp_bos(ptr): return __builtin_object_size(ptr, __SSP_FORTIFY_LEVEL > 1)

def __ssp_bos0(ptr): return __builtin_object_size(ptr, 0)

__SOCK_SIZE__ = 16
def IN_CLASSA(a): return ((((in_addr_t) (a)) & 0x80000000) == 0)

IN_CLASSA_NET = 0xff000000
IN_CLASSA_NSHIFT = 24
IN_CLASSA_HOST = (0xffffffff & ~IN_CLASSA_NET)
IN_CLASSA_MAX = 128
def IN_CLASSB(a): return ((((in_addr_t) (a)) & 0xc0000000) == 0x80000000)

IN_CLASSB_NET = 0xffff0000
IN_CLASSB_NSHIFT = 16
IN_CLASSB_HOST = (0xffffffff & ~IN_CLASSB_NET)
IN_CLASSB_MAX = 65536
def IN_CLASSC(a): return ((((in_addr_t) (a)) & 0xe0000000) == 0xc0000000)

IN_CLASSC_NET = 0xffffff00
IN_CLASSC_NSHIFT = 8
IN_CLASSC_HOST = (0xffffffff & ~IN_CLASSC_NET)
def IN_CLASSD(a): return ((((in_addr_t) (a)) & 0xf0000000) == 0xe0000000)

def IN_MULTICAST(a): return IN_CLASSD(a)

IN_MULTICAST_NET = 0xF0000000
def IN_EXPERIMENTAL(a): return ((((in_addr_t) (a)) & 0xe0000000) == 0xe0000000)

def IN_BADCLASS(a): return ((((in_addr_t) (a)) & 0xf0000000) == 0xf0000000)

INADDR_NONE = 0xffffffff
IN_LOOPBACKNET = 127
INADDR_LOOPBACK = 0x7f000001
def IN_LOOPBACK(a): return ((((in_addr_t) (a)) & 0xff000000) == 0x7f000000)

INADDR_UNSPEC_GROUP = 0xe0000000
INADDR_ALLHOSTS_GROUP = 0xe0000001
INADDR_ALLRTRS_GROUP = 0xe0000002
INADDR_MAX_LOCAL_GROUP = 0xe00000ff
INET_ADDRSTRLEN = 16

# Included from asm/byteorder.h

# Included from stdint.h

# Included from sys/_intsup.h
def __STDINT_EXP(x): return __##x##__

def __STDINT_EXP(x): return x

signed = +0
unsigned = +0
char = +0
short = +1
__int20 = +2
int = +2
long = +4
__INT8 = "hh"
__INT8 = "h"
__INT8 = "l"
__INT8 = "ll"
__INT16 = "h"
__INT16 = "l"
__INT16 = "ll"
__INT32 = "l"
__INT32 = "ll"
__INT64 = "l"
__INT64 = "ll"
__FAST8 = "hh"
__FAST8 = "h"
__FAST8 = "l"
__FAST8 = "ll"
__FAST16 = "h"
__FAST16 = "l"
__FAST16 = "ll"
__FAST32 = "l"
__FAST32 = "ll"
__FAST64 = "l"
__FAST64 = "ll"
__LEAST8 = "hh"
__LEAST8 = "h"
__LEAST8 = "l"
__LEAST8 = "ll"
__LEAST16 = "h"
__LEAST16 = "l"
__LEAST16 = "ll"
__LEAST32 = "l"
__LEAST32 = "ll"
__LEAST64 = "l"
__LEAST64 = "ll"
__int_least8_t_defined = 1
__int_least16_t_defined = 1
__int_least32_t_defined = 1
__int_least64_t_defined = 1
__int_fast8_t_defined = 1
__int_fast8_t_defined = 1
__int_fast16_t_defined = 1
__int_fast16_t_defined = 1
__int_fast32_t_defined = 1
__int_fast32_t_defined = 1
__int_fast64_t_defined = 1
__int_fast64_t_defined = 1
__int_fast8_t_defined = 1
__int_fast16_t_defined = 1
__int_fast32_t_defined = 1
__int_fast64_t_defined = 1
INTPTR_MAX = (__STDINT_EXP(LONG_MAX))
INTPTR_MIN = (-__STDINT_EXP(LONG_MAX) - 1)
INT8_MIN = (-128)
INT8_MAX = (127)
UINT8_MAX = (255)
INT_LEAST8_MIN = (-128)
INT_LEAST8_MAX = (127)
UINT_LEAST8_MAX = (255)
INT16_MIN = (-32768)
INT16_MAX = (32767)
UINT16_MAX = (65535)
INT_LEAST16_MIN = (-32768)
INT_LEAST16_MAX = (32767)
UINT_LEAST16_MAX = (65535)
INT32_MIN = (-2147483647L-1)
INT32_MAX = (2147483647L)
INT32_MIN = (-2147483647-1)
INT32_MAX = (2147483647)
INT_LEAST32_MIN = (-2147483647L-1)
INT_LEAST32_MAX = (2147483647L)
INT_LEAST32_MIN = (-2147483647-1)
INT_LEAST32_MAX = (2147483647)
INT64_MIN = (-9223372036854775807L-1L)
INT64_MAX = (9223372036854775807L)
INT_LEAST64_MIN = (-9223372036854775807L-1L)
INT_LEAST64_MAX = (9223372036854775807L)
INT_FAST8_MIN = (-__STDINT_EXP(INT_MAX)-1)
INT_FAST8_MAX = (__STDINT_EXP(INT_MAX))
INT_FAST8_MIN = INT_LEAST8_MIN
INT_FAST8_MAX = INT_LEAST8_MAX
UINT_FAST8_MAX = UINT_LEAST8_MAX
INT_FAST16_MIN = (-__STDINT_EXP(INT_MAX)-1)
INT_FAST16_MAX = (__STDINT_EXP(INT_MAX))
INT_FAST16_MIN = INT_LEAST16_MIN
INT_FAST16_MAX = INT_LEAST16_MAX
UINT_FAST16_MAX = UINT_LEAST16_MAX
INT_FAST32_MIN = (-__STDINT_EXP(INT_MAX)-1)
INT_FAST32_MAX = (__STDINT_EXP(INT_MAX))
INT_FAST32_MIN = INT_LEAST32_MIN
INT_FAST32_MAX = INT_LEAST32_MAX
INT_FAST64_MIN = (-__STDINT_EXP(INT_MAX)-1)
INT_FAST64_MAX = (__STDINT_EXP(INT_MAX))
INT_FAST64_MIN = INT_LEAST64_MIN
INT_FAST64_MAX = INT_LEAST64_MAX
INTMAX_MAX = INT64_MAX
INTMAX_MIN = INT64_MIN
SIG_ATOMIC_MIN = (-__STDINT_EXP(INT_MAX) - 1)
SIG_ATOMIC_MAX = (__STDINT_EXP(INT_MAX))
PTRDIFF_MAX = (__STDINT_EXP(LONG_MAX))
PTRDIFF_MIN = (-PTRDIFF_MAX - 1)
def INT8_C(x): return __INT8_C(x)

def UINT8_C(x): return __UINT8_C(x)

def INT8_C(x): return x

def UINT8_C(x): return x

def UINT8_C(x): return x##U

def INT16_C(x): return __INT16_C(x)

def UINT16_C(x): return __UINT16_C(x)

def INT16_C(x): return x

def UINT16_C(x): return x

def UINT16_C(x): return x##U

def INT32_C(x): return __INT32_C(x)

def UINT32_C(x): return __UINT32_C(x)

def INT32_C(x): return x##L

def UINT32_C(x): return x##UL

def INT32_C(x): return x

def UINT32_C(x): return x##U

def INT64_C(x): return __INT64_C(x)

def UINT64_C(x): return __UINT64_C(x)

def INT64_C(x): return x##L

def UINT64_C(x): return x##UL

def INT64_C(x): return x##LL

def UINT64_C(x): return x##ULL

def INTMAX_C(x): return __INTMAX_C(x)

def UINTMAX_C(x): return __UINTMAX_C(x)

def INTMAX_C(x): return x##L

def UINTMAX_C(x): return x##UL

def INTMAX_C(x): return x##LL

def UINTMAX_C(x): return x##ULL

def __constant_ntohl(x): return \

def __constant_ntohs(x): return \

def __constant_htonl(x): return __constant_ntohl(x)

def __constant_htons(x): return __constant_ntohs(x)

def ntohl(x): return \

def ntohs(x): return \

def htonl(x): return \

def htons(x): return \

def LOOPBACK(x): return (((x) & htonl(0xff000000)) == htonl(0x7f000000))

def MULTICAST(x): return (((x) & htonl(0xf0000000)) == htonl(0xe0000000))


# Included from cygwin/in6.h
INET6_ADDRSTRLEN = 46
def IN6_IS_ADDR_UNSPECIFIED(addr): return \

def IN6_IS_ADDR_LOOPBACK(addr): return \

def IN6_IS_ADDR_LINKLOCAL(addr): return \

def IN6_IS_ADDR_SITELOCAL(addr): return \

def IN6_IS_ADDR_V4MAPPED(addr): return \

def IN6_IS_ADDR_V4COMPAT(addr): return \

def IN6_IS_ADDR_MC_NODELOCAL(addr): return \

def IN6_IS_ADDR_MC_LINKLOCAL(addr): return \

def IN6_IS_ADDR_MC_SITELOCAL(addr): return \

def IN6_IS_ADDR_MC_ORGLOCAL(addr): return \

def IN6_IS_ADDR_MC_GLOBAL(addr): return \

IN6ADDR_ANY_INIT = { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 }
IN6ADDR_LOOPBACK_INIT = { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1 }
