= Pull Quote Inline Macro Extension
:a-pullquote-text: A pull quote is a purely visual technique, and therefore should not change the structure of the body.
:b-pullquote-text: It's important to note that pull quotes are merely visual in presentation and should not appear twice in the text.

A pull quote is a typographical technique in which an excerpt or quote from an article is duplicated within the article using a different formatting style so that it jumps out at the reader.

q:>[{a-pullquote-text}]
Blatantly copying the excerpt of the pull quote into it's own element is not the way to go.
{a-pullquote-text}
Next to that, a structural representation of the excerpt would be seen twice by people using feed readers or services like Instapaper, as well as be re-read for people who use screen readers.
So how can we best author this into our markup?

Here's a more realistic example of how you might use a pull quote.
q:<[{b-pullquote-text}]
When writing longform posts, I find it helpful to include pull quotes to help readers easily identify the topics covered in each section.
Some prefer to break things up with lots of headings, and while this seems to be a trend it doesn't work so well for long form prose.
{b-pullquote-text}
That is why it a CSS only technique for styling pull quotes is preferable.
Octopress includes a handy pull quote plugin to make this easy for you. 

// ideally, we want the syntax below; need to be able to contribute text to paragraph (not just substitution)
////
A pull quote is a typographical technique in which an excerpt or quote from an article is duplicated within the article using a different formatting style so that it jumps out at the reader.

Blatantly copying the excerpt of the pull quote into it's own element is not the way to go.
q:>.^[{a-pullquote-text}]
Next to that, a structural representation of the excerpt would be seen twice by people using feed readers or services like Instapaper, as well as be re-read for people who use screen readers.
So how can we best author this into our mark-up?

Here's a more realistic example of how you might use a pull quote.
When writing longform posts, I find it helpful to include pull quotes to help readers easily identify the topics covered in each section.
Some prefer to break things up with lots of headings, and while this seems to be a trend it doesn't work so well for long form prose.
q:<.^[{b-pullquote-text}]
That is why it a CSS only technique for styling pull quotes is preferable.
Octopress includes a handy pull quote plugin to make this easy for you. 
////

// could also consider this form
Here's a more realistic example of how you might use a pull quote.
q:<[precede="When writing longform posts, I find it helpful to include pull quotes to help readers easily identify the topics covered in each section.
Some prefer to break things up with lots of headings, and while this seems to be a trend it doesn't work so well for long form prose.",
pull="{b-pullquote-text}"]
That is why it a CSS only technique for styling pull quotes is preferable.
Octopress includes a handy pull quote plugin to make this easy for you. 

// or this one

////
[pullquote]
Here's a more realistic example of how you might use a pull quote.
When writing longform posts, I find it helpful to include pull quotes to help readers easily identify the topics covered in each section.
Some prefer to break things up with lots of headings, and while this seems to be a trend it doesn't work so well for long form prose.
q:<[{b-pullquote-text}]
That is why it a CSS only technique for styling pull quotes is preferable.
Octopress includes a handy pull quote plugin to make this easy for you. 
////
