#! /bin/sh
set -v
if [ -n "$1" ]; then
    eval $PYTHON_FOR_BUILD ../../Tools/scripts/h2py.py -i "'(u_long)'" /${TRIPLET}/include/stddef.h
else
    eval $PYTHON_FOR_BUILD ../../Tools/scripts/h2py.py -i "'(u_long)'" /usr/include/netinet/in.h
fi
