/**
 * This is a simple class that demonstrate the
 * use of source-highlight to produce javadoc
 * embeddable code:
 *
 * <!-- Generated by Source-highlight -->
 * <pre><tt> 
 * <i><font color="#9A1900">/* </font></i>
 * <i><font color="#9A1900">   this is an example of code to be included</font></i>
 * <i><font color="#9A1900">   in the javadoc documentation of SimpleClass</font></i>
 * <i><font color="#9A1900">&#42;/</font></i>
 * <b><font color="#000080">import</font></b> simpleclass<font color="#990000">.*;</font>
 *
 * <i><font color="#9A1900">// code snippet</font></i>
 * SimpleClass s <font color="#990000">=</font> <b><font color="#0000FF">new</font></b> <b><font color="#000000">SimpleClass</font></b><font color="#990000">(</font><font color="#993399">150</font><font color="#990000">);</font>
 * <b><font color="#0000FF">if</font></b> <font color="#990000">(</font>s <font color="#990000">==</font> <b><font color="#0000FF">null</font></b> <font color="#990000">&amp;&amp;</font> <b><font color="#0000FF">true</font></b><font color="#990000">)</font> <font color="#FF0000">{</font>
 *     <b><font color="#0000FF">throw</font></b> <b><font color="#0000FF">new</font></b> <b><font color="#000000">SimpleClassException</font></b><font color="#990000">(</font><font color="#FF0000">"failed to create"</font><font color="#990000">);</font>
 * <font color="#FF0000">}</font>
 * System<font color="#990000">.</font>out<font color="#990000">.</font><b><font color="#000000">println</font></b><font color="#990000">(</font><font color="#FF0000">"this is a simple class"</font> <font color="#990000">+</font> s<font color="#990000">);</font>
 * </tt></pre>
 *
 * The previous example code was formatted with Source-highlight
 */
public class SimpleClass {
    // nothing interesting :-)
}
