name: sync

on:
  schedule:
    - cron: "57 2 * * *"
  workflow_dispatch:
    inputs:
      debug_with_ssh_key:
        description: 'Public SSH key to use to debug failures'
        required: false

env:
  GIT_CONFIG_PARAMETERS: "'user.name=Git for Windows Build Agent' 'user.email=ci@git-for-windows.build' 'windows.sdk64.path=${{ github.workspace }}' 'windows.sdk32.path=' 'http.sslbackend=schannel' 'core.autocrlf=false' 'checkout.workers=16'"
  HOME: "${{ github.workspace }}\\home\\git-ci"
  MSYSTEM: MSYS

jobs:
  sync:
    if: github.repository_owner == 'git-for-windows' || github.event.inputs.debug_with_ssh_key != ''
    runs-on: windows-latest
    environment: sync
    steps:
      - name: clone git-sdk-64
        uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Update all Pacman packages
        shell: pwsh
        run: |
          & .\update-via-pacman.ps1
      - name: use git-sdk-64's Bash and git.exe
        run: "usr\\bin\\bash.exe -lc 'cygpath -aw /usr/bin >>$GITHUB_PATH && cygpath -aw /cmd >>$GITHUB_PATH'"
      - name: commit & push SDK
        shell: bash
        run: |
          set -x &&
          sh -x .github/commit-sdk.sh commit &&
          git push origin ${{ github.ref }}
      - name: use MSYS2 for tmate
        if: failure() && github.event.inputs.debug_with_ssh_key != ''
        run: "usr\\bin\\bash.exe -lc 'cygpath -aw /c/msys64/usr/bin >>$GITHUB_PATH'"
      - name: Debug using tmate
        if: failure() && github.event.inputs.debug_with_ssh_key != ''
        shell: bash
        run: |
          # Install tmate
          pacman -Sy --noconfirm tmate openssh &&

          # Restrict SSH access to the "actor", i.e. the GitHub user who triggered this workflow
          mkdir -p ~/.ssh &&
          echo '${{github.event.inputs.debug_with_ssh_key}}' >~/.ssh/authorized_keys &&

          # Generate an SSH key (needed for tmate)
          echo -e 'y\n' | ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa &&

          # Start tmate session
          export CHERE_INVOKING=1 &&
          tmate -S /tmp/tmate.sock -a ~/.ssh/authorized_keys new-session -d &&
          tmate -S /tmp/tmate.sock wait tmate-ready &&

          # Print SSH invocation every 5 seconds, until tmate session has terminated
          while test -e /tmp/tmate.sock
          do
            tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
            sleep 5
          done
